### ISSUE TITLE
Astro integration?

### ISSUE THREAD

**Issue by unbiased-dev** [mayank99/ecsstatic#3]
I tried adding this to astro by doing

```
import { defineConfig } from "astro/config";
import { ecsstatic } from "@acab/ecsstatic/vite";

// https://astro.build/config
export default defineConfig({
  vite: {
    plugins: [ecsstatic()],
  },
});
```

thought it would work oob but nope

I get

```
If you're seeing this error, it is likely your bundler isn't configured correctly.
File:
	/Users/user/code/projectname/node_modules/@acab/ecsstatic/index.js:3:9
Code:
	2 | function css(templates, ...args) {
	> 3 |   throw new Error(
			|         ^
		4 |     `If you're seeing this error, it is likely your bundler isn't configured correctly.`
		5 |   );
		6 | }
Stacktrace:
Error: If you're seeing this error, it is likely your bundler isn't configured correctly.
	at Proxy.css (file:///Users/user/code/projectname/node_modules/@acab/ecsstatic/index.js:3:9)
	at eval (/Users/user/code/projectname/src/pages/index.astro:12:43)
	at renderPage (file:///Users/user/code/projectname/node_modules/astro/dist/runtime/server/render/page.js:89:36)
	at renderPage (file:///Users/user/code/projectname/node_modules/astro/dist/core/render/core.js:81:26)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async renderPage (file:///Users/user/code/projectname/node_modules/astro/dist/core/render/dev/index.js:108:10)
	at async handleRoute (file:///Users/user/code/projectname/node_modules/astro/dist/vite-plugin-astro-server/route.js:152:20)
	at async run (file:///Users/user/code/projectname/node_modules/astro/dist/vite-plugin-astro-server/request.js:46:14)
	at async runWithErrorHandling (file:///Users/user/code/projectname/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
	at async handleRequest (file:///Users/user/code/projectname/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:3)

```

**Comment by mayank99** [comment]
hey @unbiased-dev. are you trying to use this in an astro file? that will not work, by design. astro already has its way of scoping+colocating CSS. if you try it in JSX files in your astro project, it should work.

**Comment by mayank99** [comment]
i've now added multiple examples of astro:
- [astro + react](https://stackblitz.com/github/mayank99/ecsstatic/tree/main/demos/astro-react?file=src%2FApp.tsx)
- [astro + solid](https://stackblitz.com/github/mayank99/ecsstatic/tree/main/demos/astro-solid?file=src%2FApp.tsx)

**Comment by mayank99** [comment]
added experimental support for astro files in [`v0.3.0`](https://github.com/mayank99/ecsstatic/releases/tag/v0.3.0). see sandbox: https://stackblitz.com/edit/github-7ejjud?file=src%2Fpages%2Findex.astro

still would not recommend this pattern but it can be useful in some cases i guess
